###Create
POST http://localhost:3333/race
Content-Type: application/json

{
    "originPoint": "oga maguila",
    "endPoint": "fiorella",
    "timeStart":"2024-04-21T18:57:29.499Z",
    "seats": 2,
    "userId": "a2d676d6-d213-4a3f-801d-060ab214b126",
    "carId": "dd8b2ad9-fdc8-407b-9db7-201419af48bb"
}

###Update
PUT http://localhost:3333/race/6dd31952-46cf-4e45-9cab-52a66e55d20a
Content-Type: application/json

{
    "originPoint": "oga maguila",
    "endPoint": "fiorella2",
    "timeStart": "20:03",
    "userId": "4118f928-54ba-48f5-a957-65fadaf860c4",
    "carId": "0a32eb3f-c81e-4658-8450-ed6852f8a833"
}

###Delete
DELETE http://localhost:3333/race/40b44593-ead1-40c9-91fd-2b9937c198df

###Get
GET http://localhost:3333/race/

###Get all
GET http://localhost:3333/race