POST http://localhost:3333/user
Content-Type: application/json

{
    "name": "Calvo",
    "email": "tomas1",
    "password": "A1234567.a"
}

###Update
PUT http://localhost:3333/users/3911a759-cce8-4f5b-936d-a16eb2811103
Content-Type: application/json

{
    "name": "calvofelipepoderosoN555o000me",
    "email": "novoemail@calvo.com",
    "password": "NovaS.enha123a"
}

###Delete
DELETE http://localhost:3333/users/a937ad56-1e25-4902-b516-9c6ee844b5e2s

###Get all
GET http://localhost:3333/users

### Get User
GET http://localhost:3333/users/becf790f-4ccb-4c0a-affe-37da8157984e
