###Create
POST http://localhost:3333/race
Content-Type: application/json

{
    "originPoint": "oga maguila",
    "endPoint": "fiorella",
    "timeStart":"2024-05-21T18:57:29.499Z",
    "seats": 2,
    "userId": "a2d676d6-d213-4a3f-801d-060ab214b126",
    "carId": "dd8b2ad9-fdc8-407b-9db7-201419af48bb"
}

###Update
PUT http://localhost:3333/race/40b44593-ead1-40c9-91fd-2b9937c198df
Content-Type: application/json

{
    "originPoint": "oga1 maguila1",
    "endPoint": "fiorella2",
    "timeStart": "2024-04-21T21:20:55.831Z",
    "seats": 5
}

###Delete
DELETE http://localhost:3333/race/40b44593-ead1-40c9-91fd-2b9937c198df

###Get
GET http://localhost:3333/race/

###Get all
GET http://localhost:3333/race