###Create
POST http://localhost:3333/car
Content-Type: application/json

{
    "plate": "hoo1111",
    "description": "claysono2@em",
    "userId": "a2d676d6-d213-4a3f-801d-060ab214b126"
}

###Update
PUT http://localhost:3333/car
Content-Type: application/json

{
    "plate": "Calvo",
    "description": "claysono2@email.com",
    "userId": "A1234567.a"
}

###Delete
DELETE http://localhost:3333/car

###Get
GET http://localhost:3333/car/

###Get all
GET http://localhost:3333/car/user/a2d676d6-d213-4a3f-801d-060ab214b126