###Create
POST http://localhost:3333/car
Content-Type: application/json

{
    "plate": "hoo1111",
    "description": "claysono2@em",
    "userId": "8b25a5b4-1a87-4be8-905d-373bce9ba5c2"
}

###Update
PUT http://localhost:3333/car
Content-Type: application/json

{
    "plate": "Calvo",
    "description": "claysono2@email.com",
    "userId": "A1234567.a"
}

###Delete
DELETE http://localhost:3333/car

###Get
GET http://localhost:3333/car/

###Get all
GET http://localhost:3333/car/user/8b25a5b4-1a87-4be8-905d-373bce9ba5c2