###Create
POST http://localhost:3333/car
Content-Type: application/json

{
    "plate": "Liz3107",
    "description": "2127",
    "userId": "c4e10876-8517-4677-a069-ca4af243bfba"
}

###Update
PUT http://localhost:3333/car/206ca71a-55fd-4386-a7dd-d03a596e6a5a
Content-Type: application/json

{
    "plate": "hoo1111",
    "description": "claysono2@em",
    "mainCar": true
}

###Delete
DELETE http://localhost:3333/car/f7806a02-bcac-4407-8111-3654384835bc

###Get
GET http://localhost:3333/car/c4e10876-8517-4677-a069-ca4af243bfba

###Get all
GET http://localhost:3333/car/user/c4e10876-8517-4677-a069-ca4af243bfba