-- AlterTable
ALTER TABLE "car" ALTER COLUMN "plate" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "race" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
